on:
  youtube:
    channel_id:
      - UCFKDEp9si4RmHFWJW1vYsMA #Etho
      - UCZ9x-z3iOnIbJxVpm1rsu2A #Iskall
      - UCodkNmk9oWRTIYZdr_HuSlg #Scar
      - UCu17Sme-KE87ca9OTzP0p7g #Beef
      - UCPK5G4jeoVEbUp5crKJl6CQ #Zedaph
      - UCcJgOennb0II4a_qi9OMkRA #Keralis
      - UCDpdtiUfcdUCzokpRWORRqA #Rendog
    playlist_id:
      - PLoH7Sjb8-XEhkvoAO9AuSxVTzI4mjm6b2 #Cubfan
      - PLvh8CGg6LWwqDwmDxZwCxsEkoEluAlAsc #Docm77
      - PLgj0MXHeQpb8KImbZzXDt0dnugiz1aOMQ #False
      - PLfim1Ac_MuxZkX_ibQCc59EGJj-fyUUKd #GeminiTay
      - PL9heRuhTVdQRMlSWZOalzcsdiQ6a93sYD #iJevin
      - PL7On8E0_x1tpitQoqpUay6FFzHpPUjIQi #JoeHills
      - PLxAyA97FNoKKRzhFu2B20bsOatAKm69KF #PearlecentMoon
      - PLFDYDXHl7Us91k8tXW-RPKjsrVXm38agF #stress
      - PLVO4L4qtJmBqmtvYc63HlwABXnn-JT3r3 #ZombieCleo
      - PL7VmhWGNRxKhcYT-uZBY5mb0SQH8jvSXh #Xisumavoid
      - PLrp4YiBloNz7nBSFiLJZhHWFdPFPT3xbR #TinFoilChef
      - PLmtS5lzk1pBR_NBsqSeHoQy7UOLnxTSHt #Xbcrafted 
      - PL2XncHqN_7yJhlp6JgHAQG4M5LJmhmZlW #Bdubs
      - PLFm1tTY1NA4ebglc7QWni3Vx6Zzdx0PQu #Mumbo
      - PLU2851hDb3SEbbc0Zx5KTD6-heWGGaKrb #Grian
      - PL8t707flkqpfRW-KEWIjQnIWs_akYpmI6 #Tango
      - PL0Z8otuXXj_3PuWDk_sjiUJ_Q8PcmwWJ4 #ImpulseSV
      - PLriprjos26pv_SyO1NLg_W8LqkbqKruXb #Hypo
      - PL3e14exB92LIQIqOBEUeLNiP6Bci4-xcO #Welsknight 
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: "${{ secrets.DISCORD_WEBHOOK }}"
          method: 'POST'
          data: {
              "content":"<<<${{on.youtube.outputs.author}}>>> Uploaded a new Hermitcraft video: <<<${{on.youtube.outputs.title}}>>> \n**Link**: <<<${{on.youtube.outputs.link}}>>>"
              }
